# yamllint disable rule:line-length

name: Recent PECL Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "35 2,6,10,14,18,22 * * *"

jobs:
  check_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: yaml
          tools: none

      - name: Checkout
        uses: actions/checkout@v3

      # see https://github.com/marketplace/actions/import-gpg
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true

      - name: Fetch PECL releases
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          bin/update-latest-releases

      - name: Commit latest releases
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          bin/commit-latest-releases
