# yamllint disable rule:line-length

name: Recent PECL Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "35 2,6,10,14,18,22 * * *"

jobs:
  check_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: yaml
          tools: none

      # see https://github.com/marketplace/actions/import-gpg
      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Fetch & Commit PECL releases
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          bin/update-latest-releases
          if [[ -f "commit.txt" ]]; then
            git config push.autoSetupRemote true
            git stash
            rightnow=$(date '+%F_%R')
            git checkout -b "releases-${rightnow}"
            git stash pop
            git add rest .etags data
            git commit -F commit.txt
            git push
            gh pr create --fill --base main
            rm commit.txt
            sleep 3
            gh pr merge --auto --merge
          fi

      - name: Commit latest releases
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |

